title = "CETSA pipeline configuration file"

[controls]
vehicle = "DMSO"
nonsenolytic = [ "Myricetin",]

[outputs]
outdir = "C:/Users/piercetf/Projects/senocetsa_outputs2"
logdir = "C:/Users/piercetf/Projects/senocetsa_outputs2"

[inputs]
use_cache = false

[inputs.cached]
data = "C:/Users/piercetf/Projects/CachedCETSAData/Complete CETSA analysis w F-37-4_Report_Delaney_Default (Normal).tsv"
candidates = "C:/Users/piercetf/Projects/CachedCETSAData/Candidates.tsv"

[inputs.uncached]
data = "C:/Users/piercetf/Projects/CachedCETSAData/Complete CETSA analysis w F-37-4_Report_Delaney_Default (Normal).tsv"
candidates = "C:/Users/piercetf/Projects/CachedCETSAData/Candidates.tsv"
